### ISSUE TITLE
nan issue

### ISSUE THREAD

**Issue by manojsmkg** [wblgers/hmm_speech_recognition_demo#2]
while running the train_GMMHMM I'm getting nan values.And in predicting it is showing following error
ValueError: startprob_ must sum to 1.0 (got nan)
So what is error

**Comment by Yujiayuan1010** [comment]
I also encountered the same problem.
Have you solved it?
Could you give me some suggestions?

**Comment by wblgers** [comment]
Please refer to https://github.com/hmmlearn/hmmlearn/issues/276

**Comment by wblgers** [comment]
I've noticed in the README, this section '2. Tricky bug workaround in hmmlearn'

**Comment by Yujiayuan1010** [comment]
> I've noticed in the README, this section '2. Tricky bug workaround in hmmlearn'

Thank you soooooooooo much to your reply!
I've just solve the problem!!!

**Comment by wblgers** [comment]
> > I've noticed in the README, this section '2. Tricky bug workaround in hmmlearn'
> 
> Thank you soooooooooo much to your reply!
> I've just solve the problem!!!

You are welcome
